---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by suho.
--- DateTime: 2022-10-17 오후 8:50
---
---
--local a = windowInit(800,600,"My Game")
--
--print("Hello, World")

print(window)

window.Init(800,600,"title")

print(window.update)

--window.size = point(-1,-1)