---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by suho.
--- DateTime: 2022-10-17 오후 8:50
---
---
--local a = windowInit(800,600,"My Game")
--
--print("Hello, World")

print(window)

--local window = window(700, 600, "title")
--
--window.init = function()
--    
--end

window.Init(800,600,"title")

window.Update = function(dt)
    --print(dt)
end

--window.size = point(-1,-1)